### ISSUE TITLE
utils.go:70: undefined: Asset

### ISSUE THREAD

**Issue by therealbill** [robinmonjo/sc-redis#2]
I've not been able to find where this should be defined at.

**Comment by robinmonjo** [comment]
you need to make the redis-rootfs target in the makefile. Asset is from go-bindata that convert the rootfs tar into []byte so it can directly be embedded in the binary. Take a look at setup.sh the provisionning script used to setup a Vagrant box and the Makefile, it shows that it downloads the rootfs from the docker-hub then it uses go-bindata. It's not vendored in the project as it turns to be a pretty big file, that can be "easily" re-created.
